# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c3a972f66a1f8a14815c8d7fa58f08d82090b2e2615e22651ab031923c017bd89969852549607f8032b5ff93bc637795db97e8fa091fad0a498f3e726cce41

test:
  secret_key_base: 2e536cfa68b6d38538ce532bbc79045b3d62abd4de79778b5a50c8cbb02543544b9af3819547641f8322dd46740ab21eee060190b33da15321e329ff195b5df5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
